// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm-badges': string;
  'mBadges': string;
}
export const cssExports: CssExports;
export default cssExports;
