// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm-badge': string;
  mBadge: string;
}
export const cssExports: CssExports;
export default cssExports;
