// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beta': string;
  'column-split': string;
  'columnSplit': string;
  'gamma': string;
  'm-article-preview-headline': string;
  'm-article-preview-headline-link': string;
  'mArticlePreviewHeadline': string;
  'mArticlePreviewHeadlineLink': string;
  'mol-mobile': string;
  'molMobile': string;
}
export const cssExports: CssExports;
export default cssExports;
