// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article-preview-headline_large': string;
  'article-preview-headline_mobile': string;
  'article-preview-headline_small': string;
  articlePreviewHeadlineLarge: string;
  articlePreviewHeadlineMobile: string;
  articlePreviewHeadlineSmall: string;
  'm-article-preview-headline': string;
  'm-article-preview-headline-link': string;
  mArticlePreviewHeadline: string;
  mArticlePreviewHeadlineLink: string;
}
export const cssExports: CssExports;
export default cssExports;
