// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm-plus': string;
  mPlus: string;
}
export const cssExports: CssExports;
export default cssExports;
