// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm-img': string;
  'm-img-video': string;
  'm-img-video_loaded': string;
  'mImg': string;
  'mImgVideo': string;
  'mImgVideoLoaded': string;
}
export const cssExports: CssExports;
export default cssExports;
