// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'm-badge': string;
  'm-bullet-icon': string;
  'm-live': string;
  'm-live-bullet-text': string;
  mBadge: string;
  mBulletIcon: string;
  mLive: string;
  mLiveBulletText: string;
}
export const cssExports: CssExports;
export default cssExports;
